name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GAME_VERSION: EMERALD
      GAME_REVISION: 0
      GAME_LANGUAGE: ENGLISH
      MODERN: 0
      COMPARE: 0   # Disable checksum compare
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout syms
        if: ${{ github.event_name == 'push' }}
        uses: actions/checkout@v3
        with:
          path: symbols
          ref: symbols

      - name: Checkout agbcc
        uses: actions/checkout@v3
        with:
          path: agbcc
          repository: pret/agbcc

      - name: Install binutils
        run: |
          sudo apt update
          sudo apt install gcc-arm-none-eabi binutils-arm-none-eabi libpng-dev

      - name: Install agbcc
        run: |
          ./build.sh
          ./install.sh ../
        working-directory: agbcc

      - name: Build ROM
        run: make -j$(nproc) compare=0   # completely skips checksum

      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: pokeemerald.gba
          path: pokeemerald.gba
