name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GAME_VERSION: EMERALD
      GAME_REVISION: 0
      GAME_LANGUAGE: ENGLISH
      MODERN: 0
      COMPARE: 0   # Completely skip checksum
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Checkout symbols (if push)
        if: ${{ github.event_name == 'push' }}
        uses: actions/checkout@v3
        with:
          path: symbols
          ref: symbols

      - name: Checkout agbcc
        uses: actions/checkout@v3
        with:
          path: agbcc
          repository: pret/agbcc

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc-arm-none-eabi binutils-arm-none-eabi libpng-dev

      - name: Install agbcc
        run: |
          ./build.sh
          ./install.sh ../
        working-directory: agbcc

      - name: Build ROM (ignore errors)
        run: |
          make -j$(nproc) compare=0 || echo "Build step failed, ignoring SHA1 errors"

      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: pokeemerald.gba
          path: pokeemerald.gba
